### ISSUE TITLE
Support for jquery-migrate 1.3.0

### ISSUE THREAD

**Issue by pratikpparikh** [MoOx/webpack-easy-config#2]
Dear Contributor,

```
     Can you please create easy-webpack configuration for jquery-migrate 1,3,0 to support jQuery 3.0?
```

Regards,
Pratik Parikh

**Comment by MoOx** [comment]
What?

**Comment by pratikpparikh** [comment]
please close this, as this was a mistake.

On Mon, Jul 11, 2016 at 8:27 AM, Maxime Thirouin notifications@github.com
wrote:

> What?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/MoOx/webpack-easy-config/issues/2#issuecomment-231719893,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABHKawHHN4xroktc6YgnKpZUKv9stRQVks5qUja4gaJpZM4JJTzQ
> .

## 

Pratik Parikh
- Mantra - Keep It Simple and Straightforward
